### ISSUE TITLE
Workaround for task name `test`

### ISSUE THREAD

**Issue by arinhouck** [benkiefer/ember-cli-gradle-plugin#14]
I already have a gradle build that uses the task `test` so the build errors with this plugin. Is there a workaround to change it to emberTest? Relatively new to gradle.

Also was curious if this plugin has potential to be compatible with Java 7?

**Comment by benkiefer** [comment]
I'd like as much as possible to model the project after an existing gradle plugin, preferably the [Java plugin](https://docs.gradle.org/current/userguide/java_plugin.html). Section, 45.3. Java plugin specifically.

It's been in the back of my head for awhile now, but I think this is a good reason to do it so that there is a standard that I'm compliant-ish with.

So, the structure will be something like:
- Build
  - Check
    - Test
      - bowerUpdate
      - bowerInstall
      - npmInstall
  - Assemble
    - emberBuild
      - bowerUpdate
      - bowerInstall
      - npmInstall  

With the existing up-to-date checks taking care of preventing duplicate executions of a task (as they do today).

What are you doing in your test task that ember is not doing so that I can try and help you hook into that lifecycle? For example, at my office we have a task called JsDependency check which is used to ensure licenses are appropriate for the projects we depend on (task is called JsLicenseCheck).

In order to hook that task into the lifecycle I described above. I would apply the plugin, define my task, and then outside of the execution say something like:

```
 check.dependsOn("JsLicenseCheck")
```

Then the plugins check task will execute my additive task.

Would that work for you?

**Comment by arinhouck** [comment]
Yes that should work. I will try out, but I also have another issue with this plugin requiring Java 8. Is there a workaround or service I can change to make it compatible with Java 7?

**Comment by benkiefer** [comment]
I'll take a look at the java 7 issue. Should be able to just set the java target version.

**Comment by benkiefer** [comment]
Quick update on this. I'm hoping to get to it this weekend. Been a busy week at work.

**Comment by benkiefer** [comment]
@arinhouck Everything should be ready to go in version 3.0.0 of the plugin. I did a major version bump because of the task structure change. Should work on 1.7 now based on me changing the target java version. Let me know if you have any issues.
