### ISSUE TITLE
allow configuration of the phantomjs port

### ISSUE THREAD

**Issue by bentrility** [benkiefer/ember-cli-gradle-plugin#20]
-1 doesn't work anymore, use zero and allow an override.

**Comment by iNaD** [comment]
It's possible to override it. I use the following solution since several months (add it to your `build.gradle`):

```
embercli {
  testArguments = ["--test-port=0"]
}
```

You can add any argument that is accepted by `ember t`. You can see the defaults used for tests and build @ [EmberCliPlugin.groovy](https://github.com/benkiefer/ember-cli-gradle-plugin/blob/master/src/main/groovy/com/kiefer/gradle/EmberCliPlugin.groovy#L210).
